---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang
  commands:
  - go test
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  host:
    path: /mnt/go

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: linux_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=git-${DRONE_COMMIT_SHA:0:8}" -a -o build/${DRONE_REPO_NAME}_linux_amd64
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=${DRONE_TAG##v}" -a -o release/${DRONE_REPO_NAME}_linux_amd64
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    files: release/*
  when:
    event:
    - tag

volumes:
- name: gopath
  host:
    path: /mnt/go

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
type: docker
name: linux_arm64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=git-${DRONE_COMMIT_SHA:0:8}" -a -o build/${DRONE_REPO_NAME}_linux_arm64
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=${DRONE_TAG##v}" -a -o release/${DRONE_REPO_NAME}_linux_arm64
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    files: release/*
  when:
    event:
    - tag

volumes:
- name: gopath
  host:
    path: /mnt/go

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
type: docker
name: linux_arm

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=git-${DRONE_COMMIT_SHA:0:8}" -a -o build/${DRONE_REPO_NAME}_linux_arm
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.version=${DRONE_TAG##v}" -a -o release/${DRONE_REPO_NAME}_linux_arm
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    files: release/*
  when:
    event:
    - tag

volumes:
- name: gopath
  host:
    path: /mnt/go

trigger:
  branch:
  - master

depends_on:
- testing

...
